title: Finn J.T. de Lange
description: Statistician & Researcher Portfolio

# Tell Jekyll not to enforce automated theme structures over your custom HTML
theme: null

kramdown:
  input: GFM
  math_engine: mathjax
